add two action

diff --git a/.github/actions/ppml-occlum-k8s-exampletests-action/action.yaml b/.github/actions/ppml-occlum-k8s-exampletests-action/action.yaml
--- a/.github/actions/ppml-occlum-k8s-exampletests-action/action.yaml
+++ b/.github/actions/ppml-occlum-k8s-exampletests-action/action.yaml
@@ -7,9 +7,7 @@ runs:
     - name: Run tests
       shell: bash
       run: |
-        docker pull 10.239.45.10/arda/intelanalytics/bigdl-ppml-trusted-big-data-ml-scala-occlum:2.2.0-SNAPSHOT
-        docker tag 10.239.45.10/arda/intelanalytics/bigdl-ppml-trusted-big-data-ml-scala-occlum:2.2.0-SNAPSHOT intelanalytics/bigdl-ppml-trusted-big-data-ml-scala-occlum:2.2.0-SNAPSHOT
-
+        docker pull intelanalytics/bigdl-ppml-trusted-big-data-ml-scala-occlum:2.2.0-SNAPSHOT
         export NO_PROXY=10.239.45.10:8081,10.112.231.51,10.239.45.10,172.168.0.205
         export kubernetes_master_url=172.168.0.205
 
@@ -21,6 +19,8 @@ runs:
         status_4_spark_gbt=1
         status_5_spark_gbt_criteo=1
         status_6_spark_tpch=1
+        status_7_pyspark_sklearn=1
+        status_8_pyspark_sql=1
 
         if [ $status_1_spark_pi -ne 0 ]; then
           echo "################## start spark pi"
@@ -105,10 +105,41 @@ runs:
             kubectl delete pods `kubectl get pods | grep spark-tpch-test | awk '{print $1}'`
           fi
         fi
+        
+        if [ $status_7_pyspark_sklearn -ne 0 ]; then
+          echo "################## start pyspark sklearn"
+          echo "example.7 pyspark sklearn"
+          bash run_pyspark_sklearn_example.sh
+          if [ "`kubectl get pods | grep pyspark-sklearn-test | awk '{print $1}'`" != "" ]; then
+            sklearn_driver=`kubectl get pods | grep pyspark-sklearn-test | awk '{print $1}'`
+          fi
+          kubectl logs $sklearn_driver | egrep 'mean_squared_error'
+          status_7_pyspark_sklearn=$(echo $?)
+          if [ "`kubectl get pods | grep pyspark-sklearn-test | awk '{print $1}'`" != "" ]; then
+            kubectl delete pods `kubectl get pods | grep pyspark-sklearn-test | awk '{print $1}'`
+          fi
+        fi
+        
+        if [ $status_8_pyspark_sql -ne 0 ]; then
+          echo "################## start pyspark SQL example"
+          echo "example.8 pyspark sql"
+          bash run_pyspark_sql_example.sh
+          if [ "`kubectl get pods | grep pyspark-sql-test | awk '{print $1}'`" != "" ]; then
+            sql_driver=`kubectl get pods | grep pyspark-sql-test | awk '{print $1}'`
+          fi
+          kubectl logs $sql_driver | egrep 'Example API finished'
+          status_8_pyspark_sql=$(echo $?)
+          if [ "`kubectl get pods | grep pyspark-sql-test | awk '{print $1}'`" != "" ]; then
+            kubectl delete pods `kubectl get pods | grep pyspark-sql-test | awk '{print $1}'`
+          fi
+        fi
 
         echo "status_1_spark_pi $status_1_spark_pi"
         echo "status_2_spark_lr $status_2_spark_lr"
-        #echo "status_3_spark_sql $status_3_spark_sql"
+        echo "status_3_spark_sql $status_3_spark_sql"
         echo "status_4_spark_gbt $status_4_spark_gbt"
         echo "status_5_spark_gbt_criteo $status_5_spark_gbt_criteo"
         echo "status_6_spark_tpch $status_6_spark_tpch"
+        echo "status_7_pyspark_sklearn $status_7_pyspark_sklearn"
+        echo "status_8_pyspark_sql $status_8_pyspark_sql"
+
