runner bash

diff --git a/.github/workflows/stable-diffusion-winlog.yml b/.github/workflows/stable-diffusion-winlog.yml
--- a/.github/workflows/stable-diffusion-winlog.yml
+++ b/.github/workflows/stable-diffusion-winlog.yml
@@ -14,4 +14,14 @@ jobs:
         run: |
           wget ftp://10.112.231.51:8821/stable-diffusion/ui-test.log --ftp-user=${{ secrets.FTP_USERNAME }} --ftp-password=${{ secrets.FTP_PASSWORD }}
           cat ui-test.log
+          content=$( cat "ui-test.log" )
           rm ui-test.log
+          if [[ " content " =~ "6 passed "]]
+            then
+              echo "All tests passed"
+              exit 0
+            else
+              echo "Some tests failed"
+              exit 1
+          fi
+          
