Update test_report.yml

diff --git a/.github/workflows/test_report.yml b/.github/workflows/test_report.yml
--- a/.github/workflows/test_report.yml
+++ b/.github/workflows/test_report.yml
@@ -55,18 +55,14 @@ jobs:
           export KERAS_BACKEND=tensorflow
           cd scala
           mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.optim" "-Dtest=com.intel.analytics.bigdl.dllib.optim.*Test" test -P spark_3.x -Dspark.version=3.1.2
-    - uses: ./
+    - name: Check pwd
+      run: pwd
+    - name: Test Report    
+      uses: actions/upload-artifact@v2
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        artifact: test-results
-        name: Workflow Report
-        path: '*.xml'
-        reporter: jest-junit
-#     - name: Test Report    
-#       uses: actions/upload-artifact@v2
-#       if: success() || failure()        # run this step even if previous step failed
-#       with:
-#         name: test-results
-#         path: jest-junit.xml
+        name: test-results
+        path: target/surefire-reports/*.xml
       #uses: dorny/test-reporter@v1
       #if: success() || failure()    # run this step even if previous step failed
       #with:
